disabled_rules:
- trailing_whitespace
- force_try
- force_cast
- identifier_name
- multiple_closures_with_trailing_closure
opt_in_rules:
- empty_count
- empty_string
excluded:
- Carthage
- Pods
- SwiftLint/Common/3rdPartyLib
identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
line_length:
    warning: 300
    error: 400
    ignores_function_declarations: true
    ignores_comments: true
    ignores_urls: true
function_body_length:
    warning: 300
    error: 500
function_parameter_count:
    warning: 8
    error: 8
type_body_length:
    warning: 300
    error: 500
file_length:
    warning: 5000
    error: 6000
    ignore_comment_only_lines: true
cyclomatic_complexity:
    warning: 15
    error: 25
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)



